bug: missing nix settings on srv
- home manager would error with:
error: The option
`home-manager.users.dustin.home.stateVersion' is
used but not defined
- it was missing the
`nixcfg.home-manager.enable = true;`

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
	modified:   systems/srv/config/default.nix