bug:
Error: could not load client settings

  Caused by:
      failed to deserialize: enum SearchMode does not have variant constructor directory

  Location:
      atuin-client/src/settings.rs:474:26

Changes to be committed:
	modified:   home/modules/fish/default.nix